name: Continuous Deployment

on:
  workflow_run:
    workflows: [ Continuous Intergration ]
    types: [ completed ]
    tags: [ v*.*.* ]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Retrieve artifacts from intergration
        uses: actions/download-artifact@v3
        with:
          name: jar
          path: build/libs/

      - name: Create changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/log.config.js

      - name: Deploys artifacts
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          # TODO: Add Modrinth and Curseforge deployment
          name: Stormfest ${{ github.ref_name }}
          changelog: ${{ steps.changelog.outputs.changes }}
          files-primary: build/libs/*

          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          loaders: fabric
          game-versions: ~1.19
          java: 17


    