name: Continuous Deployment

on:
  pull_request:
  push:
    tags: 
      - v*.*.*
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      
      - name: Permit Gradle Wrapper to run
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Create changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/log.config.js

      - name: Deploy
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: DKknxXqy
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 545658
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          name: Stormfest ${{ github.ref_name }}
          changelog: ${{ steps.changelog.outputs.changes }}
          files-secondary:

          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          loaders: |
            fabric
            
          game-versions: |
            1.19
            1.19.1
            1.19.2
          
          java: |
            17