name: Continuous Intergration

on: 
  pull_request:
  push:
    branches:
      - 'dev'
    
jobs:
  build:
    strategy:
      matrix:
        java: [
          17,
        ]
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      
      - name: Permit Gradle Wrapper to run
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build