name: Continuous Intergration

on: [ push, pull_request ]

jobs:
  build:
    runs-on: [ ubuntu-20.04, windows-2022 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distrubution: adopt
          java-version: 17
      
      - name: Permit Gradle Wrapper to run
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build
